---

name: code linter

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: 'ansible-algernon'

jobs:
  pycodestyle:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version:
          - "3.10"
          - "3.11"
          - "3.12"

    steps:
      - name: check out the codebase.
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python_version }}"

      - name: update pip
        run: |
          python3 -m pip install --upgrade pip

      - name: install pycodestyle
        run: |
          python3 -m pip install pycodestyle

      - name: run pycodestyle
        run: |
          pycodestyle $PWD --config=.config/pycodestyle.cfg --verbose --statistics --count --exclude=.git,.github,molecule
          # pycodestyle --config=.config/pycodestyle.cfg --statistics --count --exclude=test_*.py .

  yamllint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: check out the codebase.
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: install yamllint
        run: |
          python3 -m pip install yamllint
          python3 -m pip install ansible-lint

      - name: run yamllint
        run: |
          yamllint .

  ansible-lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: check out the codebase.
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: install ansible-lint
        run: |
          python3 -m pip install ansible-lint

      - name: run ansible lint
        run:
          ansible-lint .

...
